apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: banking-system
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: banking-account-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
              name: http
          envFrom:
            - configMapRef:
                name: account-service-config
            - secretRef:
                name: account-service-secret
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 10
