apiVersion: v1
kind: Secret
metadata:
  name: account-service-secret
  namespace: banking-system
  labels:
    app: account-service
type: Opaque
stringData:
  DATABASE_USERNAME: "account_user"
  DATABASE_PASSWORD: "account_pass"
  RABBITMQ_PASSWORD: "guest"
